# Generated by Django 5.2 on 2025-05-15 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_classrooms_class_membership_assignments'),
        ('users', '0002_customuser_isstudent'),
    ]

    operations = [
    ]
