# Generated by Django 5.2 on 2025-05-15 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_merge_20250516_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignments',
            name='total_Marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assignments',
            name='users',
            field=models.ManyToManyField(related_name='assignmentsUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classrooms',
            name='users',
            field=models.ManyToManyField(related_name='classrooms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('submitted_url', models.URLField()),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.assignments')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Class_Membership',
        ),
    ]
