# Generated by Django 5.2 on 2025-05-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_assignments_descriptionurl_assignments_duedate_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='users',
            new_name='user',
        ),
        migrations.AddField(
            model_name='classrooms',
            name='description',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
